### ISSUE TITLE
Test-Line

### ISSUE THREAD

**Issue by polybassa** [emundo/scapy-packet_viewer#13]
Hi, what is this line doing?
https://github.com/emundo/scapy-packet_viewer/blob/f91cf2a3d470f9deeab535cac36d520c3cec1018/scapy_packet_viewer/edit_view.py#L217

This crashes the viewer.

**Comment by TH-eMundo** [comment]
Sorry it looks like I messed up merging @akorb's refactored tests

**Comment by TH-eMundo** [comment]
I have manually merged @akorb's refactored tests now. Sorry for the inconvenience.
